lib: [
  "_build/install/default/lib/pxshot/META"
  "_build/install/default/lib/pxshot/dune-package"
  "_build/install/default/lib/pxshot/opam"
  "_build/install/default/lib/pxshot/pxshot.a"
  "_build/install/default/lib/pxshot/pxshot.cma"
  "_build/install/default/lib/pxshot/pxshot.cmi"
  "_build/install/default/lib/pxshot/pxshot.cmt"
  "_build/install/default/lib/pxshot/pxshot.cmti"
  "_build/install/default/lib/pxshot/pxshot.cmx"
  "_build/install/default/lib/pxshot/pxshot.cmxa"
  "_build/install/default/lib/pxshot/pxshot.ml"
  "_build/install/default/lib/pxshot/pxshot.mli"
]
libexec: [
  "_build/install/default/lib/pxshot/pxshot.cmxs"
]
doc: [
  "_build/install/default/doc/pxshot/LICENSE"
  "_build/install/default/doc/pxshot/README.md"
]
